### ISSUE TITLE
Timeout for a simple case

### ISSUE THREAD

**Issue by giltho** [comby-tools/comby#145]
**Describe the bug**
Comby will time out with most input files, even small ones, with a simple pattern :
```
:[x] = __builtin_annot_intval("symb_int", :[x]);
```

I've been using comby a lot recently and it works wonderfully. In particular the following pattern works without any issue :
```
int :[x] = __builtin_annot_intval("symb_int", :[x]);
```

**Reproducing**
Here's a [link](https://comby.live/index.html#%7B%22source%22%3A%22%2F*%20START%20TESTS%20*%2F%5Cn%5Cnstatic%20List%20*list1%3B%5Cnstatic%20List%20*list2%3B%5Cn%5Cnint%20cmp(void%20const%20*e1%2C%20void%20const%20*e2)%5Cn%7B%5Cn%20%20%20%20int%20i%20%3D%20*(*((int**)%20e1))%3B%5Cn%20%20%20%20int%20j%20%3D%20*(*((int**)%20e2))%3B%5Cn%5Cn%20%20%20%20if%20(i%20%3C%20j)%5Cn%20%20%20%20%20%20%20%20return%20-1%3B%5Cn%20%20%20%20if%20(i%20%3D%3D%20j)%5Cn%20%20%20%20%20%20%20%20return%200%3B%5Cn%20%20%20%20return%201%3B%5Cn%7D%5Cn%5Cnint%20zero_if_ptr_eq(void%20const%20*e1%2C%20void%20const%20*e2)%5Cn%7B%5Cn%20%20%20%20return%20!(e1%20%3D%3D%20e2)%3B%5Cn%7D%5Cn%5Cnvoid%20*copy(void%20*e1)%5Cn%7B%5Cn%20%20%20%20int%20*cp%20%3D%20(int%20*)%20malloc(sizeof(int))%3B%5Cn%20%20%20%20*cp%20%3D%20*((int*)%20e1)%3B%5Cn%20%20%20%20return%20cp%3B%5Cn%7D%5Cn%5Cnbool%20pred1(const%20void%20*e)%5Cn%7B%5Cn%20%20%20%20return%20*(int*)e%20%3D%3D%200%3B%5Cn%7D%5Cn%5Cnbool%20pred2(const%20void%20*e)%5Cn%7B%5Cn%20%20%20%20return%20*(int*)e%20%3E%203%3B%5Cn%7D%5Cn%5Cn%5Cnint%20va%2C%20vb%2C%20vc%2C%20vd%2C%20ve%2C%20vf%2C%20vg%2C%20vh%3B%5Cn%5Cnvoid%20setup_tests()%20%7B%5Cn%20%20%20%20%5Cn%20%20%20%20list_new(%26list1)%2C%5Cn%20%20%20%20list_new(%26list2)%3B%5Cn%5Cn%20%20%20%20va%20%3D%20__builtin_annot_intval(%5C%22symb_int%5C%22%2C%20va)%3B%5Cn%20%20%20%20vb%20%3D%20__builtin_annot_intval(%5C%22symb_int%5C%22%2C%20vb)%3B%5Cn%20%20%20%20vc%20%3D%20__builtin_annot_intval(%5C%22symb_int%5C%22%2C%20vc)%3B%5Cn%20%20%20%20vd%20%3D%20__builtin_annot_intval(%5C%22symb_int%5C%22%2C%20vd)%3B%5Cn%20%20%20%20ve%20%3D%20__builtin_annot_intval(%5C%22symb_int%5C%22%2C%20ve)%3B%5Cn%20%20%20%20vf%20%3D%20__builtin_annot_intval(%5C%22symb_int%5C%22%2C%20vf)%3B%5Cn%20%20%20%20vg%20%3D%20__builtin_annot_intval(%5C%22symb_int%5C%22%2C%20vg)%3B%5Cn%20%20%20%20vh%20%3D%20__builtin_annot_intval(%5C%22symb_int%5C%22%2C%20vh)%3B%5Cn%5Cn%20%20%20%20int%20*a%20%3D%20(int*)%20malloc(sizeof(int))%3B%5Cn%20%20%20%20int%20*b%20%3D%20(int*)%20malloc(sizeof(int))%3B%5Cn%20%20%20%20int%20*c%20%3D%20(int*)%20malloc(sizeof(int))%3B%5Cn%20%20%20%20int%20*d%20%3D%20(int*)%20malloc(sizeof(int))%3B%5Cn%5Cn%20%20%20%20*a%20%3D%20va%3B%5Cn%20%20%20%20*b%20%3D%20vb%3B%5Cn%20%20%20%20*c%20%3D%20vc%3B%5Cn%20%20%20%20*d%20%3D%20vd%3B%5Cn%5Cn%20%20%20%20list_add(list1%2C%20a)%3B%5Cn%20%20%20%20list_add(list1%2C%20b)%3B%5Cn%20%20%20%20list_add(list1%2C%20c)%3B%5Cn%20%20%20%20list_add(list1%2C%20d)%3B%5Cn%5Cn%20%20%20%20a%20%3D%20(int*)%20malloc(sizeof(int))%3B%5Cn%20%20%20%20b%20%3D%20(int*)%20malloc(sizeof(int))%3B%5Cn%20%20%20%20c%20%3D%20(int*)%20malloc(sizeof(int))%3B%5Cn%20%20%20%20d%20%3D%20(int*)%20malloc(sizeof(int))%3B%5Cn%5Cn%20%20%20%20*a%20%3D%20ve%3B%5Cn%20%20%20%20*b%20%3D%20vf%3B%5Cn%20%20%20%20*c%20%3D%20vg%3B%5Cn%20%20%20%20*d%20%3D%20vh%3B%5Cn%5Cn%20%20%20%20list_add(list2%2C%20a)%3B%5Cn%20%20%20%20list_add(list2%2C%20b)%3B%5Cn%20%20%20%20list_add(list2%2C%20c)%3B%5Cn%20%20%20%20list_add(list2%2C%20d)%3B%5Cn%7D%5Cn%5Cnvoid%20teardown_test()%20%7B%5Cn%20%20list_destroy_cb(list1%2C%20free)%3B%5Cn%20%20list_destroy(list2)%3B%5Cn%7D%5Cn%5Cn%5Cnvoid%20CHECK_EQUAL_C_STRING(char*%20e1%2C%20char*%20e2)%20%7B%5Cn%20%20%20%20ASSERT(strcmp(e1%2C%20e2)%20%3D%3D%200)%3B%5Cn%7D%5Cn%5Cnint%20main()%20%7B%5Cn%5Cn%20%20%20%20setup_tests()%3B%5Cn%5Cn%20%20%20%20ASSUME(%20vc%20!%3D%20va%20%26%26%20vc%20!%3D%20vb%20%26%26%20vc%20!%3D%20vd)%3B%5Cn%5Cn%20%20%20%20int%20*rm%3B%5Cn%20%20%20%20list_get_at(list1%2C%202%2C%20(void*)%20%26rm)%3B%5Cn%20%20%5Cn%20%20%20%20ListIter%20iter%3B%5Cn%20%20%20%20list_iter_init(%26iter%2C%20list1)%3B%5Cn%5Cn%20%20%20%20int%20*e%3B%5Cn%20%20%20%20while%20(list_iter_next(%26iter%2C%20(void*)%20%26e)%20!%3D%20CC_ITER_END)%20%7B%5Cn%20%20%20%20%20%20%20%20if%20(*e%20%3D%3D%20vc)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20list_iter_remove(%26iter%2C%20NULL)%3B%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%20%20ASSERT(3%20%3D%3D%20list_size(list1))%3B%5Cn%20%20%20%20ASSERT(0%20%3D%3D%20list_contains(list1%2C%20rm))%3B%5Cn%20%20%20%20free(rm)%3B%5Cn%20%20%20%20teardown_test()%3B%5Cn%7D%22%2C%22match%22%3A%22%3A%5Bx%5D%20%3D%20__builtin_annot_intval(%5C%22symb_int%5C%22%2C%20%3A%5Bx%5D)%3B%22%2C%22rule%22%3A%22where%20true%22%2C%22rewrite%22%3A%22klee_make_symbolic(%26%3A%5Bx%5D%2C%20sizeof(int)%2C%20%5C%22%3A%5Bx%5D%5C%22)%3B%5Cn%22%2C%22language%22%3A%22.generic%22%2C%22substitution_kind%22%3A%22in_place%22%2C%22id%22%3A0%7D) to the reproduced bug.

If I'm correct, matching should happen.
In particular, if you replace the wholes with `va`, it matches one of the elements.

**Comment by giltho** [comment]
Wait it's just me being dumb isn't it ? The pattern should be
```
:[[x]] = __builtin_annot_intval("symb_int", :[[x]]);
```
The pattern above is trying to match the whole file before the first `= __builtin_annot_intval` probably ?

I don't know if the fact that it times out is really an issue then. I guess it should still find something ?
Sorry for submitting an issue if it is not one, I'll let you decide if that should be closed.

**Comment by rvantonder** [comment]
> The pattern above is trying to match the whole file before the first = __builtin_annot_intval probably ?

Yes :) Others have run into this before so you're not alone. I think the right move might be to emit a warning for this sort of pattern. Tracking in #146. I added [a little note on this in the docs](https://comby.dev/#tips-and-tricks):

> You almost never want to start a template with :[hole], since it matches everything including newlines up to its suffix. This can make things slow. :[hole] is typically useful inside balanced delimiters.

---

>  I guess it should still find something ?

It probably would, if the timeout is higher (set with `-timeout 10` for 10 seconds). There is a performance issue related to this, which would make this operation faster, but matching everything up to the `=` is still probably not the intended operation. Hope that helps.

**Comment by giltho** [comment]
It does help ! I fixed my pattern, happy to hear a warning will be emitted and the doc improving.
Thank you for your reactivity, Comby's a great project !

**Comment by rvantonder** [comment]
Addressed in #147.
