### ISSUE TITLE
Site https://comby.dev/ linked from the title of repository – does not work

### ISSUE THREAD

**Issue by svetlyak40wt** [comby-tools/comby#148]
I can't connect to it.

**Comment by rvantonder** [comment]
Hi @svetlyak40wt! Could you send a screenshot of what you see, or describe the behavior, when you click the link? It appears to work for me on desktop and mobile browser:

![Kapture 2019-11-23 at 23 35 44](https://user-images.githubusercontent.com/888624/69491432-62728180-0e52-11ea-9d7b-dabf4801e477.gif)

**Comment by svetlyak40wt** [comment]
Hmm, now it works!
