### ISSUE TITLE
Support restrictions for matches in more structured way

### ISSUE THREAD

**Issue by elfring** [comby-tools/comby#151]
[A few restrictions are supported for “holes”](https://comby.dev/#match-syntax "Match syntax reference") already.
A search for alphanumeric characters and punctuation can be specified by a syntax which is slightly different from other filter possibilities.

I imagine that advanced filters could be specified directly after the match identifier.
* Character class
* Regular expression
* Predefined constraint

**Comment by rvantonder** [comment]
Indeed, there are lots of potential improvements around the syntax here. Did you perhaps have a chance to look at [the rationale for sytnax](https://github.com/comby-tools/comby/blob/master/docs/CONTRIBUTING.md#comby-syntax-rationale-and-proposal-guidelines)? 

> after the match identifier.

In general I think this is a good idea. One thing I've observed after experimenting with syntax here is that adding lots of things right after the identifier (like POSIX character classes) tends to reduce readability. But perhaps that is unavoidable for "advanced filters", and an acceptable tradeoff. 

- Character class

Yes, as you can see in the document I link above, the idea was to support something close to character classes. It gets problematic to support the full spectrum of character classes without break the well-formedness of balanced delimiters.

- Regular expression

Similar to above, and I give some examples about why supporting regular expression matching with holes is problematic in the document. A solution isn't yet clear to me how to handle handle those complexities.

- Predefined constraint

I think that's a neat idea! And it does not raise the same issues as the above two. It'd be nice to think more about how this could work.

**Comment by rvantonder** [comment]
Comby now supports regular expressions which takes care of a lot of lexical matching/customization, and this solution seems to work for those cases.

**Comment by elfring** [comment]
Thanks for your software extensions.

How will [the corresponding documentation](https://comby.dev/docs/advanced-usage "Advanced usage") evolve further?
