### ISSUE TITLE
Add ocamlformat config

### ISSUE THREAD

**Issue by ryanslade** [comby-tools/comby#172]
It would be great to have consistent, automatic formatting.

I've found ocamlformat to work well for me and it's integrated with dune, all you need is a `.ocamlformat` in the root of the project.

I'm using this config for my projects but really don't care what is used here as long as it is consistent:

```
profile=janestreet
let-binding-spacing=compact
```

**Comment by rvantonder** [comment]
Hey Ryan :-) I have some gripes with `ocamlformat` choices, but believe there may exist a combination of flags that will appease me. Just haven't looked into it yet. For now, this project uses `ocp-indent` which goes a long way towards formatting without being too opinionated.

**Comment by rvantonder** [comment]
(Keeping this issue open as a reminder to look into it)

**Comment by ryanslade** [comment]
I guess I've just been spoilt by gofmt over the years
