### ISSUE TITLE
Reason on live

### ISSUE THREAD

**Issue by maarekj** [comby-tools/comby#180]
**Describe the bug**
The *reason* langage is indicated in the documentation.
<img width="628" alt="Capture d’écran 2020-04-27 à 13 48 31" src="https://user-images.githubusercontent.com/1654977/80368970-cda30280-888d-11ea-8982-ebfd831c1a4d.png">.

But it is not not present on the live.
<img width="271" alt="Capture d’écran 2020-04-27 à 13 49 14" src="https://user-images.githubusercontent.com/1654977/80369027-e7dce080-888d-11ea-9e60-a7a2d88a4cdf.png">

**Reproducing**
Go to https://comby.live and note

**Expected behavior**
Reason langage should be present on the [combi.live](https://combi.live).

**Comment by rvantonder** [comment]
Thanks for catching! I added Reason. There are a handful of others missing in that list, which I'll add a bit later :-)

Fixed in https://github.com/comby-tools/comby-ui/commit/a31d6ab7317ebb4a7d27b8932bf5e8931038bff6
