### ISSUE TITLE
make (dune build --profile dev) fails for various .ml files

### ISSUE THREAD

**Issue by sogaiu** [comby-tools/comby#181]
**Describe the bug**
Attempting to build from source fails during the make step, specifically when processing `lib/matchers/omega.ml`, `lib/language/omega_rule.ml`, and `lib/rewriter/rewrite_template.ml`.

**Reproducing**
The following is an invocation of make and its output:
```
$ make
dune build --profile dev
File "lib/matchers/omega.ml", line 333, characters 12-19:
333 |           | Error _ ->
                  ^^^^^^^
Error: This pattern matches values of type ('b, 'c) result
       but a pattern was expected which matches values of type
         consume:Consume.t -> (Omega.production * 'a, string) result
File "lib/rewriter/rewrite_template.ml", line 22, characters 4-12:
22 |   | Ok label -> List.find_map label ~f:ident
         ^^^^^^^^
Error: This pattern matches values of type ('a, 'b) result
       but a pattern was expected which matches values of type
         consume:Consume.t -> (string option list, string) result
File "lib/language/omega_rule.ml", line 242, characters 4-11:
242 |   | Ok rule -> Or_error.return rule
          ^^^^^^^
Error: This pattern matches values of type ('a, 'b) Stdlib.result
       but a pattern was expected which matches values of type
         consume:Consume.t -> (expression list, string) Stdlib.result
make: *** [Makefile:4: build] Error 1
```

**Expected behavior**
I was expected the building from source to succeed.

**Additional context**
I'm using Ubuntu 19.10.

Tried a second time, but first removing ~/.opam and beginning at the first step of https://github.com/comby-tools/comby#build-from-source got similar results.

The steps I followed were:
* rm -rf ~/.opam
* log out
* log in
* opam init
* edit ~/.profile and ~/.bashrc for opam settings (I have no ~/.bash_profile)
* eval $(opam env)
* opam switch create 4.09.0 4.09.0
* eval $(opam env)
* git clone https://github.com/comby-tools/comby
* cd comby
* opam install . --deps-only -y
* eval $(opam env)
* make

**Comment by rvantonder** [comment]
Thanks for filing--this was just extremely unlucky. A newly released version of a dependency introduced breaking changes. I pushed https://github.com/comby-tools/comby/commit/995e786779f55e04eb1932fc82df66dee03d113e and it should work now. Feel free to close if it does.

**Comment by sogaiu** [comment]
Thanks for the update.

I tried again and it works now :)
