### ISSUE TITLE
OCaml 4.10 support

### ISSUE THREAD

**Issue by chenrui333** [comby-tools/comby#187]
**Describe the bug**

Currently, comby has to be compiled with ocaml < 4.10

**Reproducing**

```
[camlzip.git] synchronised from git+https://github.com/rvantonder/camlzip.git#zip64
camlzip is now pinned to git+https://github.com/rvantonder/camlzip.git#zip64 (version git)
The following dependencies couldn't be met:
  - comby → hack_parallel → ppxlib < 0.9.0 → ocaml < 4.10
      base of this switch (use `--unlock-base' to force)

No solution found, exiting
```

Full build log reference, [Mojave build](https://pipelines.actions.githubusercontent.com/revSbsLpzrFApLL6BmCvScWt72tRe3wYUv7fCdCtThtI5bydk7/_apis/pipelines/1/runs/26070/signedlogcontent/23?urlExpires=2020-07-03T21%3A19%3A37.9761569Z&urlSigningMethod=HMACV1&urlSignature=BhGlZC%2FHItNpVJ11KlK1Y%2BQjn5fl%2BrIpzuHWxtS7jPU%3D)

**Expected behavior**

Compile with ocaml 4.10 successfully

**Additional context**

PR ref: https://github.com/Homebrew/homebrew-core/pull/57386

**Comment by rvantonder** [comment]
@chenrui333 thanks for the report, will look into compiling successfully with 4.10 today.

**Comment by rvantonder** [comment]
Pushed https://github.com/comby-tools/comby/commit/0fd6de59b00988a4a452d4008150ffdc837fb704 which will compile with 4.10. I will cut a release a bit later today and that should fix it on your side.

**Comment by chenrui333** [comment]
Thanks for fixing this so quickly.

**Comment by chenrui333** [comment]
just tried your patch with ocaml 4.10, running into the following error:

```
==> opam config exec -- make release
Last 15 lines from /Users/rchen/Library/Logs/Homebrew/comby/03.opam:
2020-07-03 18:57:34 -0400

opam
config
exec
--
make
release

File "lib/parsers/comments.ml", line 16, characters 16-17:
16 |              if s = reserved_sequence then
                     ^
Error: This expression has type string but an expression was expected of type
         Core_kernel__Int.t = int
make: *** [release] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting


Error: Your Xcode (11.2.1) is outdated.
Please update to Xcode 11.3.1 (or delete it).
Xcode can be updated from the App Store.
```

**Comment by chenrui333** [comment]
Here is my diff:

```
+diff --git a/comby.opam b/comby.opam
+index 7470e54..f4c2854 100644
+--- a/comby.opam
++++ b/comby.opam
+@@ -33,8 +33,9 @@ depends: [
+ pin-depends: [
+   ["bisect_ppx.git" "git+https://github.com/aantron/bisect_ppx.git"]
+   ["mparser-comby.git" "git+https://github.com/comby-tools/mparser.git"]
+-  ["patdiff.git" "git+https://github.com/rvantonder/patdiff.git#0.12.1-patch-compatible-diffs"]
++  ["patdiff.git" "git+https://github.com/rvantonder/patdiff.git#0.13.0-patch-compatible-diffs"]
+   ["camlzip.git" "git+https://github.com/rvantonder/camlzip.git#zip64"]
++  ["hack_parallel.git" "git+https://github.com/rvantonder/hack_parallel.git#4.10"]
+ ]
+ depexts: [
+     [
```

**Comment by rvantonder** [comment]
Oops, I updated the dependencies to work with 4.10 but needed to make some other changes. Those are in https://github.com/comby-tools/comby/pull/188 and should actually fix everything now.

**Comment by chenrui333** [comment]
I see XD

**Comment by rvantonder** [comment]
@chenrui333 I've cut a 0.16.0 release to handle this. Let me know if it doesn't :)

**Comment by rvantonder** [comment]
Release 0.16.0 on brew and seems to be working, so I suspect if you try the 4.10 compiler now it'll work. Please reopen if not :)
