### ISSUE TITLE
Searching for a single file searches directory and fails on unreadable subdirectory

### ISSUE THREAD

**Issue by wasamasa** [comby-tools/comby#190]
**Describe the bug**
I've tried using comby to search a specific file by specifying its path, however it seems that the whole directory is searched instead. This shouldn't happen and has side effects, such as taking far longer than searching just the specified file (think of a directory containing many other files and subdirectories) or failing when encountering an unreadable subdirectory.

**Reproducing**
```
$ cd $(mktemp -d)
$ echo 'function test() {return 1;}' > test.js
$ mkdir forbidden
$ sudo chown nobody: forbidden
$ sudo chmod 0 forbidden
$ comby function '' test.js             
Error parsing command line:  
                                          
  (Sys_error "/tmp/tmp.xw1h1RJsQg/forbidden: Permission denied")
                     
For usage information, run 
                                                                                    
  comby -help                             
                    
```

**Expected behavior**
Comby searches the file and outputs matches and replacements.

**Additional context**
Version: 0.16.0. It doesn't appear to make a difference whether the path is specified as `test.js`, `./test.js` or `/tmp/tmp.xw1h1RJsQg/test.js`. Placing the file into its own directory and searching that works as expected, so does using reading from stdin and manually specifying the file type.

**Comment by rvantonder** [comment]
Thanks for the detailed report @wasamasa! Will look into it in the next couple of days

**Comment by rvantonder** [comment]
Had a quick look and wrote a fix in #190. Needs a test (just tried a couple of things based on the issue description). I'll merge soon anyway and add test later.

**Comment by rvantonder** [comment]
Opening the issue, so that I can close it once I cut a release :)

**Comment by rvantonder** [comment]
@wasamasa this is fixed in 0.17.0. If you use `brew`, it should be available there in a couple of days.

**Comment by wasamasa** [comment]
I'm on Arch and have confirmed the latest AUR package indeed resolves this behavior. Thanks!

**Comment by rvantonder** [comment]
TIL there is a comby package on AUR. Thanks @LawnGnome ;)
