### ISSUE TITLE
Generates invalid JSON 

### ISSUE THREAD

**Issue by volkanunsal** [comby-tools/comby#210]
**Describe the bug**
When I use the following command to generate json output for matched files, I notice that the output of several files often overlap each other.

> comby "const propTypes = {:[a]}" "{:[a]}" -f .jsx  -match-only  -json-lines > matches.json

**Reproducing**

1. Check out [this repo.](https://github.com/salesforce/design-system-react)
1. Go into `components` folder
1. Execute the command above.
1. Go to line 53. Notice that the JSON output is cut off.

<img width="771" alt="Screen Shot 2020-10-02 at 11 27 25 AM" src="https://user-images.githubusercontent.com/151600/94941001-4abc4e80-04a2-11eb-9b48-8fba5b362d91.png">

**Comment by rvantonder** [comment]
Hey, thanks for the clear report. I'm not able to reproduce, this likely has to do with output buffering for parallel processes. Could you share what operating system you're on?

In the meantime, if you add `-sequential` to your command this problem should go away (but it will be slower).

**Comment by volkanunsal** [comment]
Thanks, using it with sequential seems to have solved the issue.
