### ISSUE TITLE
comby doesn't work correctly with a single quote in haskell

### ISSUE THREAD

**Issue by Enr1g** [comby-tools/comby#217]
**Describe the bug**

A single quote in Haskell can be used not only as a delimeter for `Char` (e.g. `"asdf" == ['a','s','d','f']`) but also as a part of an identifier (e.g. `s = 1; s' = s + 1`). It seems that the current haskell matcher can't tell the second case from the first.

**Reproducing**

- Works as intended with a simple example: [here](https://bit.ly/2V9xejw).
- Doesn't match if there is a single quote in an identifier somewhere prior: [here](https://bit.ly/2JkO9ga).
- Matches again if a closing quote is added (thus restoring "quote balance"): [here](https://bit.ly/3lfGM7b).

**Expected behavior**

To match `hello` in the second example.

**Comment by rvantonder** [comment]
Hey, thanks for the note. You're right, the matcher is too strict here, expecting `'` to be balanced. I've made it less strict.

**Comment by rvantonder** [comment]
This is fixed, but not released yet. I'll release an updated version today.

**Comment by s0kil** [comment]
@rvantonder I've seen you just released the new version, is there a change log somewhere?

**Comment by rvantonder** [comment]
Hey @s0kil I was just writing it up and editing the release notes--I should probably have done that before publishing :-) Check out https://github.com/comby-tools/comby/releases/tag/1.1.0
