### ISSUE TITLE
Rewrite does write to unchanged files

### ISSUE THREAD

**Issue by cal101** [comby-tools/comby#222]
**Describe the bug**
When using rewrite in place all parsed files are written even if no changes.

**Reproducing**
Just do any rewrite and look at the file modification date.

**Expected behavior**
Leave unchanged files alone.

**Additional context**
Pull request with solution in a minute.

**Comment by cal101** [comment]
I found the fix to be incomplete.
Since this fix I (at minimum) switched to config files but maybe changed some other parameters.

At the location of the first fix "replacements" may be empty but the source was changed.

The fix for in-place file output is obvious, use:

`if (rewritten_source <> source_content) then`

But I think some other output targets suffer from the same problem: They assume replacements to be properly set,
e.g. json output

I can't follow the execution flow good enough to see why.

**Comment by rvantonder** [comment]
@cal101 if you can give a complete and minimal steps to reproduce (which we can use as setup for a test) I can have a look next time I have a chance. Thanks!

**Comment by cal101** [comment]
Sure here we come.

test1.toml:
```
[tmpl1]
match="x"
rewrite="X"

[tmpl2]
match="y"
rewrite="Y"
```

```
$ echo "x x" | comby -stats -stdin -config test1.toml -json-lines
{"uri":null,"rewritten_source":"X X\n","in_place_substitutions":[],"diff":"--- /dev/null\n+++ /dev/null\n@@ -1,1 +1,1 @@\n-x x\n+X X"}
{
  "number_of_files": 1,
  "lines_of_code": 1,
  "number_of_matches": 2,
  "total_time": 0.42891502380371094
}
```

You see the mismatch between the number_of_matchers and the empty in_place_substitutions.
That guided me to the method that sums the counts but does not concatenate the matches/replacements.
I am working on the fix but need to refresh my ML skills.

P.S.
I am struggling with comment preservation in comby and posted a question on gitter. It would be nice if you find some time for guidance.
