### ISSUE TITLE
Release windows binary

### ISSUE THREAD

**Issue by gayanper** [comby-tools/comby#233]
I'm looking into build a tool for large code changes using this. Is there a possibility to build native windows binary ?

**Comment by rvantonder** [comment]
Unfortunately there aren't plans for a native windows binary any time soon. The major blocking issue are the following dependencies:

- `core`, which uses Unix to traverse files/directories. If `comby` can be built with `core-kernel` and remove this dependency, it would help things along. It's possible to break this dependency, but needs a restructure and quite a bit of work
- `hack_parallel`, which is the library to do Unix-style fork parallelism. It'd be possible to remove parallel processing from `comby` for windows, or use OCaml multicore with windows once that's possible.

What you can use "natively" in Windows instead is `comby.js`, which is a Javascript library for the basic `comby` match/rewrite abilities, and build on top of that. I haven't had time to turn that into a CLI tool yet. Here's  a comment on the state of that, and how it could be used: https://github.com/comby-tools/comby/issues/96#issuecomment-768558178

**Comment by rvantonder** [comment]
Closing this in favor of the windows support issue https://github.com/comby-tools/comby/issues/115, let me know if you have more thoughts in that issue. Thanks!
