### ISSUE TITLE
Support predicates for matched patterns

### ISSUE THREAD

**Issue by marxin** [comby-tools/comby#268]
I have a motivation example I noticed in `binutils` and `gcc` code base:

```c
if (strncmp (var, "foo", 3) == 0))
...
```

which can be transformed to:
```c
if (startswith(var, "foo")))
```

So I would need something like `where strlen(:[string]) == :[n]`.
Would it be possible to implement that? Thanks.

**Comment by rvantonder** [comment]
Good idea--you mean for checking the length of a constant string here right? How about just an attribute on the matched part, so

`:[thing].length == 3`

**Comment by marxin** [comment]
> Good idea--you mean for checking the length of a constant string here right?

Yes, exactly.

> How about just an attribute on the matched part, so
> `:[thing].length == 3`

Works for me.

**Comment by marxin** [comment]
Any progress on this, please?

**Comment by rvantonder** [comment]
Hiya, unfortunately no, I haven't had time to do this yet. Lots of refactoring to make this easier to implement.

**Comment by marxin** [comment]
I see, thanks for working on that.

**Comment by rvantonder** [comment]
This is now available in the release here: https://github.com/comby-tools/comby/releases/tag/1.6.0. This is not available in brew yet, and I haven't updated the doc site yet, I'll close this issue once that's done. Just giving a heads up.

One small note: there's no integer comparison for comby, you can write `where :[thing].length == 3` as I wrote it there, but it is textual, and it's only possible to compare textual equality/inequality.

**Comment by rvantonder** [comment]
FYI: https://comby.dev/docs/rewrite-properties

Most of those should work with `1.6.0`, including `.length`. There were a couple of additions in `1.7.0` that aren't live via `brew install` yet but should be soon.

**Comment by marxin** [comment]
Thanks for it!
