### ISSUE TITLE
Comby's docker image does not contain the ripgrep binary

### ISSUE THREAD

**Issue by kkom** [comby-tools/comby#282]
**Describe the bug**

Comby's docker image does not contain the ripgrep binary. This makes it impossible to make use of the ripgrep pre-filtering step.

**Reproducing**

Try to invoke comby with the ripgrep binary through its docker image:

```
➜  core-events git:(master) docker run -it -w /code -v `pwd`:/code comby/comby:1.1.0 -matcher .generic -rg "-g 'gradle-wrapper.properties'" "distributionUrl=:[urlPrefix]gradle-6.:[~[\.\d]*]:[urlSuffix]" "distributionUrl=:[urlPrefix]gradle-6.8.3:[urlSuffix]"
/bin/sh: rg: not found
Error executing rg, exit status 127.
```

**Expected behavior**

Run comby on the host system (which has ripgrep installed):

```
➜  core-events git:(master) comby -matcher .generic -rg "-g 'gradle-wrapper.properties'" "distributionUrl=:[urlPrefix]gradle-6.:[~[\.\d]*]:[urlSuffix]" "distributionUrl=:[urlPrefix]gradle-6.8.3:[urlSuffix]"
------ gradle/wrapper/gradle-wrapper.properties
++++++ gradle/wrapper/gradle-wrapper.properties
@|-1,5 +1,5 ============================================================
 |distributionBase=GRADLE_USER_HOME
 |distributionPath=wrapper/dists
!|distributionUrl=https\://services.gradle.org/distributions/gradle-6.8.3-all.zip
 |zipStoreBase=GRADLE_USER_HOME
 |zipStorePath=wrapper/dists
```

**Comment by rvantonder** [comment]
Hmmm, I'm thinking that a good way to go about this is to release a separate docker image with `comby+rg`. This because currently there are reasons to have a `comby` distribution without `-rg` for use cases where image size matters, and the `-rg` option doesn't. Would that work for you?

**Comment by kkom** [comment]
Yeah, sure! I wasn’t aware that rg added so much to size! I actually did this myself anyway too, haha - just having it be officially built would be nicer :)

**Comment by rvantonder** [comment]
You can grab the docker image packaged with rg with  `docker pull comby/comby-rg`
