### ISSUE TITLE
Discrepancy between Comby.live and CLI

### ISSUE THREAD

**Issue by d4hines** [comby-tools/comby#290]
**Describe the bug**
I'm trying to strip out all comments in OCaml files. I have the a [working example on comby.live](https://comby.live/index.html#%7B%22source%22%3A%22%5Cn(**%20%5Bas_computation_pattern%20p%5D%20is%20a%20computation%20pattern%20with%20description%5Cn%20%20%20%20%5BTpat_value%20p%5D%2C%20which%20enforces%20a%20correct%20placement%20of%20pat_attributes%5Cn%20%20%20%20and%20pat_extra%20metadata%20(on%20the%20inner%20value%20pattern%2C%20rather%20than%20on%5Cn%20%20%20%20the%20computation%20pattern).%20*)%5Cnval%20as_computation_pattern%3A%20pattern%20-%3E%20computation%20general_pattern%5Cn%5Cnval%20classify_pattern_desc%3A%20'k%20pattern_desc%20-%3E%20'k%20pattern_category%5Cnval%20classify_pattern%3A%20'k%20general_pattern%20-%3E%20'k%20pattern_category%5Cn%5Cntype%20pattern_action%20%3D%5Cn%20%20%7B%20f%20%3A%20'k%20.%20'k%20general_pattern%20-%3E%20unit%20%7D%5Cnval%20shallow_iter_pattern_desc%3A%5Cn%20%20%20%20pattern_action%20-%3E%20'k%20pattern_desc%20-%3E%20unit%5Cn%5Cntype%20pattern_transformation%20%3D%5Cn%20%20%7B%20f%20%3A%20'k%20.%20'k%20general_pattern%20-%3E%20'k%20general_pattern%20%7D%5Cnval%20shallow_map_pattern_desc%3A%5Cn%20%20%20%20pattern_transformation%20-%3E%20'k%20pattern_desc%20-%3E%20'k%20pattern_desc%5Cn%5Cnval%20iter_general_pattern%3A%20pattern_action%20-%3E%20'k%20general_pattern%20-%3E%20unit%5Cnval%20iter_pattern%3A%20(pattern%20-%3E%20unit)%20-%3E%20pattern%20-%3E%20unit%5Cn%5Cntype%20pattern_predicate%20%3D%20%7B%20f%20%3A%20'k%20.%20'k%20general_pattern%20-%3E%20bool%20%7D%5Cnval%20exists_general_pattern%3A%20pattern_predicate%20-%3E%20'k%20general_pattern%20-%3E%20bool%5Cnval%20exists_pattern%3A%20(pattern%20-%3E%20bool)%20-%3E%20pattern%20-%3E%20bool%5Cn%5Cn(**%20bottom-up%20mapping%20of%20patterns%3A%20the%20transformation%20function%20is%5Cn%20%20%20%20called%20on%20the%20children%20before%20being%20called%20on%20the%20parent%20*)%22%2C%22match%22%3A%22%3A%5Bopen~%5C%5C(%5C%5C**%5D%3A%5Bany%5D%3A%5Bclose~%5C%5Cn*%5C%5C*%5C%5C)%5D%22%2C%22rule%22%3A%22where%20true%22%2C%22rewrite%22%3A%22%22%2C%22language%22%3A%22.ml%22%2C%22substitution_kind%22%3A%22in_place%22%2C%22id%22%3A0%7D) which is typically what I use to prototype a script.

However, when I run the script output by `Run in Terminal` button in Comby.live, it fails to strip the comments. For reference, i've uploaded a replica of my local files in this gist: https://gist.github.com/d4hines/2a61fe88c2a8a555157a25ae57dfce69

Thanks for any help you can provide with this!

**Reproducing**
See above links.

**Expected behavior**
Comby.live and the CLI should produce the same outputs.

**Additional context**

**Comment by rvantonder** [comment]
Hey thanks for the note and sorry about this. I've updated comby.live to stop this discrepancy from happening. With more recent CLI versions a flag is needed `-match-newline-at-toplevel` to get the same behavior (which is what the terminal button will show now). At some point the need for this flag will go away, I've been experimenting with different match behaviors to make this sort of thing less of an issue.

**Comment by rvantonder** [comment]
Also thanks for the files, I did check that the copy command works as expected

![Uploading Screen Shot 2021-05-22 at 2.39.17 PM.png…]()

**Comment by d4hines** [comment]
Cool, thanks!
