### ISSUE TITLE
Matching a block inside loops in Python

### ISSUE THREAD

**Issue by jrfaller** [comby-tools/comby#294]
**Describe the bug**
It seems there is a problem when trying to match blocks inside Python for loops.

**Reproducing**
https://bit.ly/3fKhFtK

I was thinking the :[block] meta-variable should capture both `print(elt)` statements, I am I wrong? Maybe this is related to #65?

Cheers!

**Comment by rvantonder** [comment]
You're right, indentation-sensitive matching is [not supported](https://comby.dev/docs/faq#what-about-indentation-sensitive-languages) yet. Closing in favor of #65 since that issue already tracks the missing support :-)

**Comment by jrfaller** [comment]
Thanks for you quick answer! I hope that you'll get it working it would dramatically help us in our project ;)

Cheers.

**Comment by rvantonder** [comment]
Noted, thanks for your interest! Fingers crossed I get time to hack on that soon-ish :-)
