### ISSUE TITLE
Regression: install in ubuntu docker image

### ISSUE THREAD

**Issue by jensim** [comby-tools/comby#295]
**Describe the bug**
Create dockerfile with content:
```
FROM ubuntu:20.04
RUN apt-get update && apt-get install -y \
  bash \
  curl \
  sudo \
  sed \
  libpcre3-dev \
  && rm -rf /var/lib/apt/lists/* \
  && bash -c 'bash <(curl -sL get.comby.dev)'
```
Output:
```
#4 16.75 [+] Downloading comby 1.7.0
#4 18.16 [+] Download complete.
#4 18.67 [+] Installing comby to /usr/local/bin
#4 18.75 /usr/local/bin/comby: error while loading shared libraries: libev.so.4: cannot open shared object file: No such file or directory
#4 18.76 [-] comby did not install correctly.
#4 18.76 [-] My guess is that you need to install the pcre library on your system. Try:
#4 18.76 [*] sudo apt-get install libpcre3-dev && bash <(curl -sL get.comby.dev)
```

**Reproducing**
_same as description_

**Expected behavior**
I tried to rebuild an old Dockerfile I had, and it now wasn't working. 

**Additional context**
I use a ubuntu-based fat image to run more avanced sourcegraph batch changes, and depend on this pattern to install comby in it

**Comment by cal101** [comment]
Just from looking at the error message I see that "libev.so.4" is reported missing.
I would try to find out the package that is in and install it.
The command "ldd" when run on a binrary tells the shared libs used and probably not found.

**Comment by jensim** [comment]
Hi @cal101 , and thanks for contributing to the discussion =)
The output said 
```
#4 18.76 [-] My guess is that you need to install the pcre library on your system. Try:
#4 18.76 [*] sudo apt-get install libpcre3-dev && bash <(curl -sL get.comby.dev)
```
So I added that to the Dockerfile, without success

**Comment by cal101** [comment]
I don't know so I guess.

I understand the message to be a "guess" of the reason that most often is the case when comby can't be started.

The message you get from starting comby: 
/usr/local/bin/comby: error while loading shared libraries: **libev.so.4: cannot open shared object file**: No such file or directory
indicates to me another library a missing. 

I would compare with comby Dockerfile what is installed or take a look which package does contain that and add it.

By just looking into https://github.com/comby-tools/comby/blob/master/dockerfiles/ubuntu/binary-release/Dockerfile
I see that **libev-dev** is installed.

**Comment by rvantonder** [comment]
Yeah, looks like that ubuntu install script needs to install (at least) the libev-dev dependency:

```
FROM ubuntu:20.04
RUN apt-get update && apt-get install -y \
  bash \
  curl \
  sudo \
  sed \
  libpcre3-dev \
  libev-dev \
  && rm -rf /var/lib/apt/lists/* \
  && bash -c 'bash <(curl -sL get.comby.dev)'
```

I've updated the README to list all the required external dependencies. These are:

```
sudo apt-get install autoconf libpcre3-dev pkg-config zlib1g-dev m4 libgmp-dev libev-dev libsqlite3-dev
```

Let me know if this works and we can close the issue.

**Comment by jensim** [comment]
`libpcre3-dev` + `libev-dev ` made it work again! Thanks for helping out me out once again!
