### ISSUE TITLE
comby.live broken due to CORS policy violations

### ISSUE THREAD

**Issue by elimisteve** [comby-tools/comby#326]
**Expected behavior**

I should be able to use comby.live as instructed on the site.

**Additional context**

Instead, the site doesn't show the anything in either the blue or red bottom boxes, due to this error I see in the JS console:

`Access to XMLHttpRequest at 'https://lerewriteserver.xyz:8888/rewrite' from origin 'https://comby.live' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by rvantonder** [comment]
Are you perhaps on a network with a VPN / middleware that is blocking CORS? I can't reproduce, and would probably get a looot of reports if it didn't work in the usual case.

**Comment by elimisteve** [comment]
I am no longer having this issue. Maybe I upgraded Brave and they loosened their default CORS restrictions or something; not sure. Working now, though!
