### ISSUE TITLE
Tarball checksum has changed

### ISSUE THREAD

**Issue by mseri** [comby-tools/comby#328]
In the opam repository all builds of comby-related packages are failing with invalid checksum, e.g.
```
#=== ERROR while fetching sources for comby-semantic.1.7.0 ====================#
OpamSolution.Fetch_fail("https://github.com/comby-tools/comby/archive/1.7.0.tar.gz (Bad checksum, expected md5=ee6556d8bd9b25ed0445ebe23862e48a)")

#=== ERROR while fetching sources for comby-kernel.1.7.0 ======================#
OpamSolution.Fetch_fail("https://github.com/comby-tools/comby/archive/1.7.0.tar.gz (Bad checksum, expected md5=ee6556d8bd9b25ed0445ebe23862e48a)")
```

Do you know why it changed?

**Comment by rvantonder** [comment]
The release isn't updated or changed, so no action on my side 😅. Some searching reveals that GH may not guarantee exact byte-for-byte equivalence (2018 reference, do you know if this is still the case? https://github.com/keybase/client/issues/10800#issuecomment-375831096). It might be related to timestamps and/or cache invalidation on GH side?

Has any other `opam` checksums failed recently?

**Comment by mseri** [comment]
Yeah, I think we got i to this issue. For future releases it is better to reupload the tarball as an artefact to avoid unexpected changes. In the meantime we were able to recover the old tarball from a cache backup, and updated the opam files to point to that one
