### ISSUE TITLE
Cannot install on Windows WSL (libev.so.4 not found)

### ISSUE THREAD

**Issue by Kleptine** [comby-tools/comby#329]
**Describe the bug**
I can't install comby on Windows WSL. The error message is:
``` bash
[+] Downloading comby 1.7.0
[+] Download complete.
[+] Installing comby to /usr/local/bin
/usr/local/bin/comby: error while loading shared libraries: libev.so.4: cannot open shared object file: No such file or directory
[-] comby did not install correctly.
[-] My guess is that you need to install the pcre library on your system. Try:
[*] sudo apt-get install libpcre3-dev && bash <(curl -sL get.comby.dev)
```

Naturally, I verified that libpcre3-dev is properly installed:
 ```bash
> sudo apt-get install libpcre3-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libpcre3-dev is already the newest version (2:8.39-9).
The following package was automatically installed and is no longer required:
  libfreetype6
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 221 not upgraded.
```

**Expected behavior**
It should install properly. 
The docs should probably mention this as a dependency.

I'm happy to attach any additional information here. Otherwise, my WSL installation works just fine.

I can't dig up much information on libev, in general. I'm not sure why it's not installed on my machine -- any hints?

**Comment by rvantonder** [comment]
Hi there! This change should help, which hints to install `libev` via the install script now: https://github.com/comby-tools/comby/commit/e15456616123f7ae1a51d07e622743a80afbf4ac. The updated script just needs to make it's way up to the `get.comby.dev` link. The other reference to `libev` is in the README so it should be covered :-) Thanks
