### ISSUE TITLE
Trying to match a PHP simple template

### ISSUE THREAD

**Issue by slim16165** [comby-tools/comby#334]
**This is my example source code:**

```
$plugins1 = $this->filter2->GetAdminPlugins();
            if (!empty($plugins1))
			{
				$plugins = $this->getArray_mapSplitAndTrim($plugins1);

               
			}
```

**And this is my attempt to capture it:**
```
:[var] = $this->filter2->:[method]();
if (!empty(:[var]))
{
:[p] = :[p1]
:[rest]
}
```

I can't understand why it's not working

**Comment by rvantonder** [comment]
Th trouble is that there's `:[p1] :[rest]`, which says "match anything with `:[p1]`, then whitespace (there is a newline after the `:[p1]`) then anything with `:[rest]`, then whitespace again (there is a newline after the `:[rest]`). This means matching the whitespace _twice_ in the pattern is not optional, it's required. But in the original source, there is only whitespace following `:[p1]`, this doesn't satisfy "match something, whitespace, something (maybe nothing), and whitespace again.


I realize this might sound confusing, but that's the current behavior. Best to be more specific about syntax to match on. You can consider something like this to not create a pattern to match whitespace twice:

```
:[var] = $this->filter2->:[method]();
if (!empty(:[var]))
{
:[p] = :[p1];:[rest]
}
```


example: https://bit.ly/3rhPW97

Please post further questions on this in the gitter channel https://gitter.im/comby-tools/community 😄  thank you
