### ISSUE TITLE
Typo in the doc example for rewrite rule

### ISSUE THREAD

**Issue by duchainer** [comby-tools/comby#335]
**Describe the bug**
The written example has a typo

**Reproducing**
1- Go to https://comby.dev/docs/advanced-usage#rewrite-expressions
2- Compare the second paragraph `dict(:[args]) => :[args]` with [the associated playground ](https://bit.ly/30d3Tss)

**Expected behavior**
I expect the `rewrite=` to be the same as the one in the associated playground

It should be written `dict(:[args]) => {:[args]}` instead of `dict(:[args]) => :[args]`

**Additional context**
I wasn't able to find a github repo for the documentation, so this is the next best place I suppose. :sweat_smile: 

Have a nice day :smile:

**Comment by rvantonder** [comment]
Good eye! Thanks. Fixed here: https://github.com/comby-tools/comby.dev/commit/6983968b628976298209abc77190e281932a25e7.
