### ISSUE TITLE
Difficulties connecting to comby.dev

### ISSUE THREAD

**Issue by timvahlbrock** [comby-tools/comby#364]
**Describe the bug**
Safari, Edge and Firefox currently from time to time refuse to connect to comby.dev from Germany with error messages regarding TLS Security.
Safari: Safari cannot establish a secure connection.
Edge: ERR_CONN_CLOSED
Firefox: PR_END_OF_FILE_ERROR

**Reproducing**
Open a browser and go to comby.dev. If you can connect, navigate around. Sometimes you will get a problem with the connection.

The problem can reliably be reproduced with curl:
Running `curl -L https://comby.dev --resolve 'comby.dev:443:2a09:8280:1:0:0:0:f:1705'` (connecting to the Amsterdam server) results in `curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to comby.dev:443`. Running `curl -L https://comby.dev --resolve 'comby.dev:443:34.83.23.240'` (connecting to the Oregon server) resolves without an issue.

**Expected behavior**
The site opens reliably.

**Additional context**
I'm connecting from Germany. Qualys SSL Labs shows the Amsterdam server not having security protocols in place. `curl -L comby.dev` reports `curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to comby.dev:443`

**Comment by timvahlbrock** [comment]
Problem has also been verified by other person on other network, but in same town.

**Comment by rvantonder** [comment]
Thanks for the context I'm not able to replicate in browser, but I'll look into the SSL certificate on the site host

**Comment by TrueWill** [comment]
I'm seeing this as well - verified from two devices with two browsers (Chrome/macOS and Firefox Focus/iOS).

**Comment by rvantonder** [comment]
Think I found the issue and it should be fixed (bad alias in dns records). Please reopen if you run into issues again.
