### ISSUE TITLE
Support glibc 2.28

### ISSUE THREAD

**Issue by neongreen** [comby-tools/comby#365]
Currently binary builds of Comby cannot be used on RHEL 8:

```
comby: /lib64/libm.so.6: version 'GLIBC_2.29' not found (required by comby)
```

Not sure how hard it is to fix.

**Comment by rvantonder** [comment]
Unfortunately there's no binary build available for RHEL 8 (it is for Ubuntu Linux). Right now the only way around this is to build form source, please refer to the README for that.
