### ISSUE TITLE
[non-issue] What's Omega matcher engine?

### ISSUE THREAD

**Issue by Ray-Eldath** [comby-tools/comby#368]
I am a big fan of comby, it save me from many tedious regex search and replace! I saw there's a `-omega Use Omega matcher engine.` argument on the command line but no further explanation anywhere. Just want to ask what is omega matcher engine? and is that engine better than the default one? thank you!

I post this question as an issue here (not in Gitter) is because I guess someone may have the same question as me, so this won't get asked and answered repeatedly.

**Comment by rvantonder** [comment]
It's a rewrite of the matcher engine with a different library dependency.

> is that engine better than the default one? 

Don't know 😅 At some point it might be. I don't think it has feature parity yet and could be slower or faster, I haven't tested thoroughly.

Feel free to reopen if this doesn't answer your question.
