### ISSUE TITLE
comby.live is missing version information

### ISSUE THREAD

**Issue by zdenek-crha** [comby-tools/comby#373]
**Describe the bug**

I have used comby.live to write match/rewrite rule and checked that it works with example code. But when I tried to run the same match/rewrite rule from command line, it did not match/rewrite anything.

Finding out why web/cli versions behave differently was difficult because comby.live does not show version and non-default flags it is using.

**Reproducing**

Open comby.live webpage. Look around and try to find information about comby version powering the website.

**Expected behavior**

* version deployed on comby.live webpage should be noted on page
* list of non-default flags used by comby.live should be noted on page (see below)

**Additional context**

In my case, the mismatch between comby.live and comby CLI behaviour was due to `-omega` flag.  The `v1.9.1` I used on CLI requires explicit flag to turn it on. Website turns it on automatically, but does not tell user about it.

When whitespace matching algorithm is important for match rule, the website and CLI behaviour will be different and it might trip beginner users.

**Comment by rvantonder** [comment]
Hi, thanks for this. I'll have a look, I think you're right that they are indeed on different versions!

**Comment by rvantonder** [comment]
I updated the site to have a command-line copy button, I think the difference may have been due to missing a flag `-match-newline-at-toplevel` that's needed to be backwards compatible with the latest release. When I bump the server this shouldn't be needed any more. feel free to reopen if you run into other issues!
