### ISSUE TITLE
Matching def end in Ruby

### ISSUE THREAD

**Issue by jrfaller** [comby-tools/comby#59]
**Describe the bug**
I do not manage to match a method block in ruby

**Reproducing**
Code :

```
def foo
  bar.each do end
end
```

and my matching code is : 

```
def :[m]
end
```

**Expected behavior**
The full method body to be matched but here it matches only until the end that closes the block.

**Comment by rvantonder** [comment]
Yes, thanks! This is being tracked in #35 and in progress. I'll update here when it's ready :)

**Comment by rvantonder** [comment]
I've added initial support. Grab it in the 0.7.0 release, or build from master. You can also see it in action in the `staging` version of the live demo: https://bit.ly/2XMywnl. Once it's stable I'll put it over on the live site.

So give it another try and let me know if you run into any issues :)

**Comment by jrfaller** [comment]
Nice, it works now on my simple use-case. I will try it on more complicated cases and tell you if I run into any problem.

Thanks a lot!
