### ISSUE TITLE
Dependencies missing in readme/mac

### ISSUE THREAD

**Issue by morandat** [comby-tools/comby#60]
**Describe the bug**
Dependencies missing in the readme/mac part, namely bisect_ppx & patdiff

**Reproducing**
Follow the readme on a machine with a fresh install of opam

**Expected behavior**
Exepected to build comby when following the readme ... and it doesn't

**Additional context**
I don't use ocaml in my everyday life, so I've just blindly followed the readme. I may have missed some points.

**Fix**
Used `brew install opam && opam init` ... followed the readme ... added `opam install bisect_ppx patdiff` ... Now make does the job.

(Thanks for the tool anyway :) )

**Comment by morandat** [comment]
I've retried (and re-failed) by starting with an opam switch (missed it the first time). Definitely `opam install bisect_ppx patdiff` fix-it. Maybe the later as a dep on the former ... but clearly not the other way around.

**Comment by rvantonder** [comment]
Thanks--the build dependencies diverged from the README. I've updated it in #62.
