### ISSUE TITLE
macOS binary: libpcre.1.dylib not found

### ISSUE THREAD

**Issue by wojas** [comby-tools/comby#89]
**Describe the bug**

The v0.8.0 binary does not work under macOS, because it is linked against a non-existing `/usr/local/opt/pcre/lib/libpcre.1.dylib`.

The suggested `brew install pcre` does not resolve this, because brew installs it as `/usr/local/brew/lib/libpcre.1.dylib`.

**Reproducing**

```
$ comby
dyld: Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
  Referenced from: /usr/local/bin/comby
  Reason: image not found
$ brew install pcre
...
Warning: pcre 8.43 is already installed and up-to-date
To reinstall 8.43, run `brew reinstall pcre`
$ brew reinstall pcre
...
$ comby
dyld: Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
  Referenced from: /usr/local/bin/comby
  Reason: image not found
$ find /usr/local/brew -name libpcre.1.dylib
/usr/local/brew/lib/libpcre.1.dylib
/usr/local/brew/Cellar/pcre/8.43/lib/libpcre.1.dylib
```

**Comment by wojas** [comment]
Workaround (requires Xcode):

```
$ install_name_tool -change /usr/local/opt/pcre/lib/libpcre.1.dylib /usr/local/brew/lib/libpcre.1.dylib /usr/local/bin/comby
```

**Comment by rvantonder** [comment]
Thanks for the heads-up! It seems brew may behave differently depending on Mac OS X versions. What is your Mac OS X version?

**Comment by wojas** [comment]
I'm using macOS Mojave (10.14.5).

I suspect that the issue is not with brew, but that you installed pcre from source sometime in the past, and during the build it is linking to that one instead.

**Comment by wojas** [comment]
Apparently brew does install by default under `/usr/local` nowadays. When I originally installed it, everything was installed under `/usr/local/brew` and brew just keeps installing stuff there. Or perhaps I did not use the default prefix during installation, but I don't remember doing that.

I don't see any clean solution to this other than perhaps just mentioning the workaround in the README.

Anyway, feel free to close this issue.

**Comment by wojas** [comment]
Or perhaps comby can statically link against pcre instead of using dynamic linking? It would not make the binary significantly larger.

**Comment by rvantonder** [comment]
Will think about the static linking--for now I'll add something in the install script & README when this goes wrong. Appreciate the note!

**Comment by virusdave** [comment]
FYI - i ran into this also when nix-ifying install.  Workaround here:
https://github.com/virusdave/nix-comby/blob/master/comby.nix#L60

(although i haven't yet pushed the change to use the xcode-command-line tools instead of the xcode version)

**Comment by rvantonder** [comment]
Thanks. Closing this, and tracking the general issue in #96
