### ISSUE TITLE
can not find libpcre on archlinux

### ISSUE THREAD

**Issue by xieyuheng** [comby-tools/comby#94]
`/usr/local/bin/comby: error while loading shared libraries: libpcre.so.3: cannot open shared object file: No such file or directory`

archlinux:
```
1 core/pcre 8.43-1 [installed]
    A library that implements Perl 5-style regular expressions
2 core/pcre2 10.33-1 [installed]
    A library that implements Perl 5-style regular expressions.
    2nd version
```

**Comment by xieyuheng** [comment]
```
pacman -Ql pcre | grep so
pcre /usr/lib/libpcre.so
pcre /usr/lib/libpcre.so.1
pcre /usr/lib/libpcre.so.1.2.11
pcre /usr/lib/libpcre16.so
pcre /usr/lib/libpcre16.so.0
pcre /usr/lib/libpcre16.so.0.2.11
pcre /usr/lib/libpcre32.so
pcre /usr/lib/libpcre32.so.0
pcre /usr/lib/libpcre32.so.0.0.11
pcre /usr/lib/libpcrecpp.so
pcre /usr/lib/libpcrecpp.so.0
pcre /usr/lib/libpcrecpp.so.0.0.1
pcre /usr/lib/libpcreposix.so
pcre /usr/lib/libpcreposix.so.0
pcre /usr/lib/libpcreposix.so.0.0.6
```

**Comment by rvantonder** [comment]
Unfortunately the binaries are precompiled for Ubuntu Linux and are dynamically linked. In time I will either statically link to PCRE, or provide an Arch distro. 

For now, try the following for Arch: `ln -s /usr/lib/libpcre.so /usr/lib/libpcre.so.3`

**Comment by xieyuheng** [comment]
Thank you so much.

**Comment by xieyuheng** [comment]
I am watching your stangeloop talk, it is super good talk.

(Will read "Lightweight Multi-Language Syntax Transformation with Parser Parser Combinators" soon.)

**Comment by rvantonder** [comment]
Tracking in #96

**Comment by Retkid** [comment]
> Unfortunately the binaries are precompiled for Ubuntu Linux and are dynamically linked. In time I will either statically link to PCRE, or provide an Arch distro.
> 
> For now, try the following for Arch: `ln -s /usr/lib/libpcre.so /usr/lib/libpcre.so.3`

I want to PR this but I don't know where to pr...
