### ISSUE TITLE
Show example that is not possible with regular expressions

### ISSUE THREAD

**Issue by exterm** [comby-tools/comby#95]
**Is your feature request related to a problem? Please describe.**
After seeing the presentation at Strange Loop, I was going to demonstrate `comby` to my colleagues. I sold it as "more expressive than search and replace with regular expressions". The examples I can find would all be easily implemented as regular expressions, e.g. with `sed`.

**Describe the solution you'd like**
The README should list a simple example that is not expressible as a regular expression, or would result in a very complex regular expression.

Thank you!

**Comment by exterm** [comment]
I found that the usage docs on comby.dev contain examples like that, but I think I would feature them more prominently (for example by adding one to the README), as this, for me, is the main selling point for `comby` from a user perspective.

**Comment by rvantonder** [comment]
That's a really good suggestion, I appreciate it. An example in the README would help bring the point across. Stay tuned--I'd like to dig up good example that is small but also representative and 
a little less contrived than the one in the docs.

**Comment by exterm** [comment]
I wonder if just matching on `puts(:[param])` in `puts("hello)")` would be enough?

**Comment by rvantonder** [comment]
Thank you for your suggestion @exterm, I've added a [note in the README](https://github.com/comby-tools/comby#arent-regex-approaches-like-sed-good-enough) and the docs with a hopefully straightforward and compelling example.

**Comment by exterm** [comment]
👍 thank you!
