### ISSUE TITLE
Question/Feature request

### ISSUE THREAD

**Issue by thisfred** [comby-tools/comby#97]
I was trying out comby and wanted to do the following refactoring:

```python
dict(foo=bar,baz=qux)
```
=> 

```python
{"foo": bar, "baz": qux}
```
but I can't find a way to repeatedly apply a pattern within a particular scope. Am I missing how to do this, or is this not currently possible?

**Comment by rvantonder** [comment]
It's possible, but not documented yet :) What you do is use a nested rewrite rule like this: https://bit.ly/2LY8N3z

I'll update the docs in the advanced/exerpimental feature section. For future questions feel free to head over to gitter: https://gitter.im/comby-tools/community. I appreciate this question, it's helped me to refer people to gitter when starting an issue in case it's about writing a pattern. Thanks for popping in!

**Comment by rvantonder** [comment]
For posterity: 

`dict(:[args])` -> `{:[args]}`

```
where rewrite :[args] { 
  ":[[k]]=:[[v]]" -> "\":[k]\": :[v]"
}
```

:)

**Comment by thisfred** [comment]
That's awesome, thank you!

**Comment by rvantonder** [comment]
You are very welcome. I've updated [the docs](https://comby.dev/#experimental-language-features-rewrite-expression), and used your example :)
